version: '3.7'
services:
  php:
    build: ./.docker/php-fpm
    volumes:
      - ./:/var/www/symfony:cached
      - ./logs/symfony:/var/www/symfony/var/log:cached
  nginx:
    build: ./.docker/nginx
    ports:
      - "8080:80"
    links:
      - php
    volumes:
      - ./:/var/www/symfony:cached
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.2
    environment:
      discovery.type: "single-node"
  logstash:
    image: docker.elastic.co/logstash/logstash:7.4.2
    depends_on:
      - elasticsearch
    volumes:
      - ./.docker/elk/logstash/pipelines.yml:/usr/share/logstash/config/pipelines.yml:cached
      - ./.docker/elk/logstash/conf.d:/etc/logstash/conf.d:cached
  kibana:
    depends_on:
      - elasticsearch
    image: docker.elastic.co/kibana/kibana:7.4.2
    environment:
      SERVER_NAME: localhost
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    ports:
      - "8081:5601"
